deixando fool proof

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,6 +39,14 @@ jobs:
             echo ">>> Changing to application directory: $APP_DIR"
             cd $APP_DIR || { echo "Failed to change directory to $APP_DIR"; exit 1; }
 
+            echo ">>> Check package.json diff to decide whether to delete package-lock and node_modules"
+            if git diff --name-only HEAD~1 HEAD | grep -q 'package.json\|package-lock.json'; then
+              echo "Dependencies changed, installing removing node modules and package-lock.json"
+              rm -rf node_modules package-lock.json || { echo "Failed to remove node_modules and package-lock.json"; exit 1; }
+            else
+              echo "No changes in dependencies, skipping delete package-lock.json and node_modules"
+            fi
+
             echo ">>> Git pull"
             git pull origin ${{ github.ref_name }} || { echo "Git pull failed"; exit 1; }
 
