devolvendo ao modelo inicial

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,24 +39,8 @@ jobs:
             echo ">>> Changing to application directory: $APP_DIR"
             cd $APP_DIR || { echo "Failed to change directory to $APP_DIR"; exit 1; }
 
-            echo ">>> Capturing current commit (local)"
-            OLD_COMMIT=$(git rev-parse HEAD)
-            echo "Local commit: $OLD_COMMIT"
-
             echo ">>> Git pull"
             git pull origin ${{ github.ref_name }} || { echo "Git pull failed"; exit 1; }
-
-            echo ">>> Capturing new commit (production)"
-            NEW_COMMIT=$(git rev-parse HEAD)
-            echo "Production commit: $NEW_COMMIT"
-
-            echo ">>> Check package.json diff between local and production"
-            if git diff --name-only $OLD_COMMIT $NEW_COMMIT | grep -q 'package.json\|package-lock.json'; then
-              echo "Dependencies changed, removing node modules and package-lock.json"
-              rm -rf node_modules package-lock.json || { echo "Failed to remove node_modules and package-lock.json"; exit 1; }
-            else
-              echo "No changes in dependencies, skipping delete package-lock.json and node_modules"
-            fi
 
             echo ">>> Executing nvm and installing node"
             export NVM_DIR="$HOME/.nvm"
@@ -64,8 +48,9 @@ jobs:
             nvm use 22
 
             echo ">>> Check package.json diff to decide whether to install dependencies"
-            if git diff --name-only $OLD_COMMIT $NEW_COMMIT | grep -q 'package.json\|package-lock.json'; then
+            if git diff --name-only HEAD~1 HEAD | grep -q 'package.json\|package-lock.json'; then
               echo "Dependencies changed, installing node modules"
+              rm -rf node_modules package-lock.json || { echo "Failed to remove node_modules and package-lock.json"; exit 1; }
               npm install || { echo "npm install failed"; exit 1; }
             else
               echo "No changes in dependencies, skipping npm install"
